### ISSUE TITLE
`npm install` fails

### ISSUE THREAD

**Issue by nmushegian** [ethereum/ethereumjs-lib#121]
`npm install ethereumjs-lib`

```
npm ERR! secp256k1@1.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the secp256k1@1.1.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the secp256k1 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls secp256k1
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!    <empty logfile>
npm ERR! code 1
```

**Comment by nmushegian** [comment]
it's a different package but I think @wanderer owns both

**Comment by wanderer** [comment]
@nagydani yep, I need to bump the packages. one sec!

**Comment by wanderer** [comment]
ok I bump the deps, can you see if it works now?

**Comment by nmushegian** [comment]
it works

**Comment by nmushegian** [comment]
Still some problems using it:

```
/Users/nikolai/devenv/dapple/rewrite/node_modules/bindings/bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /Users/nikolai/devenv/dapple/rewrite/node_modules/ethereumjs-tx/node_modules/secp256k1/build/secp256k1.node
 → /Users/nikolai/devenv/dapple/rewrite/node_modules/ethereumjs-tx/node_modules/secp256k1/build/Debug/secp256k1.node
 → /Users/nikolai/devenv/dapple/rewrite/node_modules/ethereumjs-tx/node_modules/secp256k1/build/Release/secp256k1.node
 → /Users/nikolai/devenv/dapple/rewrite/node_modules/ethereumjs-tx/node_modules/secp256k1/out/Debug/secp256k1.node
 → /Users/nikolai/devenv/dapple/rewrite/node_modules/ethereumjs-tx/node_modules/secp256k1/Debug/secp256k1.node
 → /Users/nikolai/devenv/dapple/rewrite/node_modules/ethereumjs-tx/node_modules/secp256k1/out/Release/secp256k1.node
 → /Users/nikolai/devenv/dapple/rewrite/node_modules/ethereumjs-tx/node_modules/secp256k1/Release/secp256k1.node
 → /Users/nikolai/devenv/dapple/rewrite/node_modules/ethereumjs-tx/node_modules/secp256k1/build/default/secp256k1.node
 → /Users/nikolai/devenv/dapple/rewrite/node_modules/ethereumjs-tx/node_modules/secp256k1/compiled/5.0.0/darwin/x64/secp256k1.node
    at bindings (/Users/nikolai/devenv/dapple/rewrite/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/Users/nikolai/devenv/dapple/rewrite/node_modules/ethereumjs-tx/node_modules/secp256k1/index.js:18:35)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/nikolai/devenv/dapple/rewrite/node_modules/ethereumjs-tx/index.js:3:15)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/nikolai/devenv/dapple/rewrite/node_modules/ethereumjs-vm/node_modules/ethereumjs-block/index.js:3:12)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/nikolai/devenv/dapple/rewrite/node_modules/ethereumjs-vm/lib/runCode.js:18:15)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/nikolai/devenv/dapple/rewrite/node_modules/ethereumjs-vm/lib/index.js:50:24)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/nikolai/devenv/dapple/rewrite/node_modules/ethereumjs-vm/index.js:1:80)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/nikolai/devenv/dapple/rewrite/node_modules/ethereumjs-lib/index.js:2:14)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/nikolai/devenv/dapple/rewrite/lib/vmtest.js:2:11)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/nikolai/devenv/dapple/rewrite/test/vmtest_test.sol:1:76)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at /usr/local/lib/node_modules/mocha/lib/mocha.js:216:27
    at Array.forEach (native)
    at Mocha.loadFiles (/usr/local/lib/node_modules/mocha/lib/mocha.js:213:14)
    at Mocha.run (/usr/local/lib/node_modules/mocha/lib/mocha.js:453:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/mocha/bin/_mocha:393:18)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3
```

**Comment by nmushegian** [comment]
works with 1.0.2
