### ISSUE TITLE
Cannot bundle using browserify

### ISSUE THREAD

**Issue by taye** [ethereum/ethereumjs-lib#78]
```
$ cat index.js
var Ethereum = require("etherumjs-lib");

$ browserify index.js -o bundle.js
Error: Cannot find module 'etherumjs-lib' from '/home/taye/test'
    at /usr/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:50:17
    at process (/usr/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:119:43)
    at /usr/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:128:21
    at load (/usr/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:60:43)
    at /usr/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:66:22
    at /usr/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:21:47
    at Object.oncomplete (fs.js:108:15)
```

`ethereumjs-lib` was installed using npm and was in `./node_modules/ethereumjs-lib` of the working directory.

**Comment by romanman** [comment]
+1

**Comment by wanderer** [comment]
There are two problems here I think.
1) is misspelling try `require("etheruemjs-lib");`
2) there was a missing dependency

I just pushed a fix for 2 to the `develop` branch. You can install it from npm by running `npm install  git+https://github.com/ethereum/ethereumjs-lib.git#develop`

**Comment by taye** [comment]
It looks like it's working well now. Thank you!
